

export const GETLIST ="GETLIST"
export const GETLIST_SUCCESS ="GETLIST_SUCCESS"
export const GETLIST_FAIL ="GETLIST_FAIL"

export const UPDATELIST ="UPDATELIST"
export const UPDATELIST_SUCCESS ="UPDATELIST_SUCCESS"
export const UPDATELIST_FAIL ="UPDATELIST_FAIL"


export const REGISTER ="REGISTER"
export const REGISTER_SUCCESS ="REGISTER_SUCCESS"
export const REGISTER_FAIL ="REGISTER_FAIL"

export const LOGIN ="LOGIN"
export const LOGIN_SUCCESS ="LOGIN_SUCCESS"
export const LOGIN_FAIL ="LOGIN_FAIL"

export const PROFILE ="PROFILE"
export const PROFILE_SUCCESS ="PROFILE_SUCCESS"
export const PROFILE_FAIL ="PROFILE_FAIL"